// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// PostSnapshot implements postSnapshot operation.
//
// Save measurements snapshot.
//
// POST /api/snapshot
func (UnimplementedHandler) PostSnapshot(ctx context.Context, req *Snapshot) (r PostSnapshotRes, _ error) {
	return r, ht.ErrNotImplemented
}
