// Code generated by ogen, DO NOT EDIT.

package api

import (
	"time"
)

// Ref: #/components/schemas/Error
type Error struct {
	Message string `json:"message"`
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

func (*Error) postSnapshotRes() {}

// Ref: #/components/schemas/NtcParams
type NtcParams struct {
	// NTC resistance at T0, ohm.
	R0 int `json:"r0"`
	// NTC base temperature, degC.
	T0 int `json:"t0"`
	// NTC B-parameter.
	B int `json:"b"`
	// Pull-up resistor, ohm.
	Pullup int `json:"pullup"`
	// ADC resolution, bits.
	AdcBits int `json:"adc_bits"`
	// Number of sensors (length of raw).
	SensorsCnt int `json:"sensors_cnt"`
}

// GetR0 returns the value of R0.
func (s *NtcParams) GetR0() int {
	return s.R0
}

// GetT0 returns the value of T0.
func (s *NtcParams) GetT0() int {
	return s.T0
}

// GetB returns the value of B.
func (s *NtcParams) GetB() int {
	return s.B
}

// GetPullup returns the value of Pullup.
func (s *NtcParams) GetPullup() int {
	return s.Pullup
}

// GetAdcBits returns the value of AdcBits.
func (s *NtcParams) GetAdcBits() int {
	return s.AdcBits
}

// GetSensorsCnt returns the value of SensorsCnt.
func (s *NtcParams) GetSensorsCnt() int {
	return s.SensorsCnt
}

// SetR0 sets the value of R0.
func (s *NtcParams) SetR0(val int) {
	s.R0 = val
}

// SetT0 sets the value of T0.
func (s *NtcParams) SetT0(val int) {
	s.T0 = val
}

// SetB sets the value of B.
func (s *NtcParams) SetB(val int) {
	s.B = val
}

// SetPullup sets the value of Pullup.
func (s *NtcParams) SetPullup(val int) {
	s.Pullup = val
}

// SetAdcBits sets the value of AdcBits.
func (s *NtcParams) SetAdcBits(val int) {
	s.AdcBits = val
}

// SetSensorsCnt sets the value of SensorsCnt.
func (s *NtcParams) SetSensorsCnt(val int) {
	s.SensorsCnt = val
}

// PostSnapshotNoContent is response for PostSnapshot operation.
type PostSnapshotNoContent struct{}

func (*PostSnapshotNoContent) postSnapshotRes() {}

// Ref: #/components/schemas/Snapshot
type Snapshot struct {
	// Client-side snapshot timestamp.
	Ts time.Time `json:"ts"`
	// BLE device name.
	Device string    `json:"device"`
	Raw    []int     `json:"raw"`
	Ntc    NtcParams `json:"ntc"`
}

// GetTs returns the value of Ts.
func (s *Snapshot) GetTs() time.Time {
	return s.Ts
}

// GetDevice returns the value of Device.
func (s *Snapshot) GetDevice() string {
	return s.Device
}

// GetRaw returns the value of Raw.
func (s *Snapshot) GetRaw() []int {
	return s.Raw
}

// GetNtc returns the value of Ntc.
func (s *Snapshot) GetNtc() NtcParams {
	return s.Ntc
}

// SetTs sets the value of Ts.
func (s *Snapshot) SetTs(val time.Time) {
	s.Ts = val
}

// SetDevice sets the value of Device.
func (s *Snapshot) SetDevice(val string) {
	s.Device = val
}

// SetRaw sets the value of Raw.
func (s *Snapshot) SetRaw(val []int) {
	s.Raw = val
}

// SetNtc sets the value of Ntc.
func (s *Snapshot) SetNtc(val NtcParams) {
	s.Ntc = val
}
